export const list = [
  {
    block: [
      "next/link",
      "next/image",
      "next/navigation",
      "@tanstack/react-router",
      "@remix-run/react",
    ],
    code: "import { defineContent, z } from 'fromsrc'; export default defineContent({dir:'docs',schema:z.object({title:z.string()})});",
    max: 130_000,
    maxgzip: 37_000,
    name: "core",
  },
  {
    code: "import { calcReadTime } from 'fromsrc/readtime'; export default calcReadTime('a b c');",
    max: 250,
    maxgzip: 170,
    name: "readtime",
  },
  {
    code: "import { scoreTerms, termIndex } from 'fromsrc/searchscore'; const data={title:'intro',slug:'/intro',description:'d',content:'text',titleIndex:termIndex(['intro']),slugIndex:termIndex(['intro']),descriptionIndex:termIndex(['d']),headingIndex:termIndex(['intro']),contentIndex:termIndex(['text'])}; export default scoreTerms(['intro'],data);",
    max: 1700,
    maxgzip: 740,
    name: "searchscore",
  },
  {
    code: "import { addDocument, createIndex, search } from 'fromsrc/searchindex'; const index=createIndex(); addDocument(index,{path:'/a',title:'a',headings:['h'],content:'body'}); export default search(index,'a');",
    max: 1400,
    maxgzip: 750,
    name: "searchindex",
  },
  {
    code: "import { normalizeQuery, searchMaxQuery, trimQuery } from 'fromsrc/searchpolicy'; export default [normalizeQuery('A   B'), trimQuery('abc'), searchMaxQuery];",
    max: 260,
    maxgzip: 170,
    name: "searchpolicy",
  },
  {
    code: "import { generateLlmsIndex } from 'fromsrc/llms'; export default generateLlmsIndex({title:'a',description:'b',baseUrl:'https://x.y'},[{title:'t',slug:'s'}]);",
    max: 600,
    maxgzip: 400,
    name: "llms",
  },
  {
    code: 'import { parseOpenApi } from \'fromsrc/openapi\'; export default parseOpenApi(\'{"openapi":"3.1.0","info":{"title":"a","version":"1"},"paths":{}}\');',
    max: 6500,
    maxgzip: 2500,
    name: "openapi",
  },
  {
    code: "import { createAlgoliaAdapter } from 'fromsrc/algolia'; export default createAlgoliaAdapter;",
    max: 3200,
    maxgzip: 1200,
    name: "algolia",
  },
  {
    code: "import { createOramaAdapter } from 'fromsrc/orama'; export default createOramaAdapter;",
    max: 3200,
    maxgzip: 1200,
    name: "orama",
  },
  {
    block: ['"react-router"', "@tanstack/react-router", "@remix-run/react"],
    code: "import { nextAdapter } from 'fromsrc/next'; export default nextAdapter;",
    max: 650,
    maxgzip: 360,
    name: "next",
  },
  {
    block: [
      "next/link",
      "next/image",
      "next/navigation",
      "@tanstack/react-router",
      "@remix-run/react",
    ],
    code: "import { reactRouterAdapter } from 'fromsrc/react-router'; export default reactRouterAdapter;",
    max: 600,
    maxgzip: 320,
    name: "reactrouter",
  },
  {
    block: [
      "next/link",
      "next/image",
      "next/navigation",
      '"react-router"',
      "@remix-run/react",
    ],
    code: "import { tanstackAdapter } from 'fromsrc/tanstack'; export default tanstackAdapter;",
    max: 650,
    maxgzip: 350,
    name: "tanstack",
  },
  {
    block: [
      "next/link",
      "next/image",
      "next/navigation",
      '"react-router"',
      "@tanstack/react-router",
    ],
    code: "import { remixAdapter } from 'fromsrc/remix'; export default remixAdapter;",
    max: 650,
    maxgzip: 340,
    name: "remix",
  },
  {
    block: [
      "next/link",
      "next/image",
      "next/navigation",
      '"react-router"',
      "@tanstack/react-router",
      "@remix-run/react",
    ],
    code: "import { astroAdapter } from 'fromsrc/astro'; export default astroAdapter;",
    max: 1250,
    maxgzip: 660,
    name: "astro",
  },
  {
    block: [
      "next/link",
      "next/image",
      "next/navigation",
      '"react-router"',
      "@tanstack/react-router",
      "@remix-run/react",
    ],
    code: "import { viteAdapter } from 'fromsrc/vite'; export default viteAdapter;",
    max: 1250,
    maxgzip: 660,
    name: "vite",
  },
];

export const external = [
  "react",
  "react/jsx-runtime",
  "next",
  "next/image",
  "next/link",
  "next/navigation",
  "react-router",
  "@tanstack/react-router",
  "@remix-run/react",
];
