import rehypeShiki from "@shikijs/rehype"
import {
	transformerMetaHighlight,
	transformerNotationDiff,
	transformerNotationFocus,
	transformerNotationHighlight,
	transformerNotationWordHighlight,
} from "@shikijs/transformers"
import type { ShikiTransformerContext } from "@shikijs/types"
import { transformerCollapse } from "fromsrc"
import {
	Accordion,
	AccordionItem,
	Alert,
	Anchor,
	Autofill,
	Avatar,
	AvatarGroup,
	AvatarStack,
	BackToTop,
	Badge,
	Banner,
	BlockMath,
	Breadcrumb,
	BulletItem,
	BulletList,
	Button,
	Callout,
	Card,
	Cards,
	Change,
	Changelog,
	Checkbox,
	CheckItem,
	CheckList,
	Code,
	CodeBlock,
	CodeGroup,
	CodeSandbox,
	CodeTab,
	CodeTabs,
	Collapsible,
	Column,
	Command,
	Compare,
	CompareRow,
	Content,
	Copyable,
	CopyBlock,
	Countdown,
	Create,
	Definition,
	DefinitionList,
	Details,
	Divider,
	Dropdown,
	Endpoint,
	Experimental,
	Feature,
	FeatureCard,
	Features,
	Feedback,
	File,
	Files,
	Flex,
	Folder,
	Frame,
	Gist,
	Github,
	Glossary,
	GlossaryItem,
	Graph,
	Grid,
	H1,
	H2,
	H3,
	H4,
	H5,
	H6,
	Highlight,
	HoverInfo,
	Important,
	InlineMath,
	Input,
	Install,
	Kbd,
	LanguageSwitch,
	Line,
	Link,
	LinkCard,
	LinkCards,
	Loading,
	Math,
	Mermaid,
	MobileNav,
	Modal,
	NavLink,
	Note,
	NumberItem,
	NumberList,
	Output,
	Pagination,
	Param,
	Popover,
	Pre,
	Progress,
	ProgressSteps,
	Properties,
	Property,
	Quote,
	Radio,
	RadioGroup,
	Rating,
	ReadTime,
	Release,
	Response,
	Screenshot,
	ScrollProgress,
	Search,
	Select,
	Shortcut,
	Show,
	Sidebar,
	Skeleton,
	SkeletonCard,
	SkeletonText,
	Spinner,
	StackBlitz,
	Status,
	StatusDot,
	Step,
	Steps,
	Switch,
	Tab,
	Table,
	TabNav,
	TabNavDropdown,
	Tabs,
	Tag,
	Tags,
	Terminal,
	Testimonial,
	Testimonials,
	Textarea,
	ThemeToggle,
	Toc,
	TocInline,
	ToastProvider,
	Tooltip,
	Tweet,
	Typed,
	TypePopup,
	TypeTable,
	Typewriter,
	Underline,
	User,
	VersionSelect,
	Video,
	YouTube,
	Zoom,
} from "fromsrc/client"
import { rehypeAnchors, remarkAlerts } from "fromsrc"
import { MDXRemote } from "next-mdx-remote/rsc"
import type { ComponentPropsWithoutRef, ReactNode } from "react"
import remarkGfm from "remark-gfm"

type HeadingProps = ComponentPropsWithoutRef<"h1"> & { children?: ReactNode }
type CodeProps = ComponentPropsWithoutRef<"code"> & { children?: ReactNode }
type PreProps = ComponentPropsWithoutRef<"pre"> & {
	children?: ReactNode
	"data-language"?: string
	"data-title"?: string
}

function getId(children: ReactNode): string {
	if (typeof children === "string") {
		return children.toLowerCase().replace(/\s+/g, "-")
	}
	return ""
}

const components = {
	h2: (props: HeadingProps) => <h2 id={getId(props.children)} {...props} />,
	h3: (props: HeadingProps) => <h3 id={getId(props.children)} {...props} />,
	h4: (props: HeadingProps) => <h4 id={getId(props.children)} {...props} />,
	code: (props: CodeProps) => {
		const text = typeof props.children === "string" ? props.children : ""
		const isInline = typeof props.children === "string" && !text.includes("\n")
		if (!isInline) return <code {...props} />
		return <code {...props} />
	},
	pre: (props: PreProps) => {
		const lang = props["data-language"] || ""
		const title = props["data-title"] || ""
		return (
			<CodeBlock lang={lang} title={title || undefined}>
				<pre {...props} />
			</CodeBlock>
		)
	},
	Install,
	Create,
	Callout,
	Steps,
	Step,
	Tabs,
	Tab,
	Cards,
	Card,
	Accordion,
	AccordionItem,
	Files,
	File,
	Folder,
	Badge,
	Banner,
	Zoom,
	CodeGroup,
	CodeTab,
	CodeTabs,
	TypeTable,
	Github,
	Tooltip,
	Video,
	Mermaid,
	TocInline,
	Kbd,
	Shortcut,
	Math,
	BlockMath,
	InlineMath,
	Endpoint,
	Param,
	Response,
	Screenshot,
	Frame,
	Property,
	Properties,
	Note,
	Important,
	Experimental,
	Changelog,
	Release,
	Change,
	Collapsible,
	Details,
	Terminal,
	Line,
	Output,
	Typed,
	YouTube,
	CodeSandbox,
	StackBlitz,
	Tweet,
	Gist,
	Quote,
	Testimonials,
	Testimonial,
	Compare,
	Column,
	CompareRow,
	Feature,
	Features,
	FeatureCard,
	Feedback,
	Graph,
	LanguageSwitch,
	Copyable,
	CopyBlock,
	DefinitionList,
	Definition,
	Glossary,
	GlossaryItem,
	Avatar,
	AvatarGroup,
	User,
	LinkCard,
	LinkCards,
	Status,
	StatusDot,
	Pagination,
	VersionSelect,
	Divider,
	Progress,
	ProgressSteps,
	Tag,
	Tags,
	CheckList,
	CheckItem,
	BulletList,
	BulletItem,
	NumberList,
	NumberItem,
	TabNav,
	TabNavDropdown,
	Show,
	Grid,
	Flex,
	Alert,
	AvatarStack,
	Command,
	Countdown,
	Dropdown,
	Highlight,
	HoverInfo,
	Loading,
	Modal,
	Popover,
	Rating,
	ScrollProgress,
	Skeleton,
	SkeletonCard,
	SkeletonText,
	Spinner,
	TypePopup,
	Typewriter,
	Underline,
	Input,
	Button,
	Select,
	Checkbox,
	Switch,
	Table,
	Autofill,
	Radio,
	RadioGroup,
	Textarea,
	Anchor,
	BackToTop,
	Breadcrumb,
	Code,
	Content,
	H1,
	H2,
	H3,
	H4,
	H5,
	H6,
	Link,
	MobileNav,
	NavLink,
	Pre,
	ReadTime,
	Search,
	Sidebar,
	ThemeToggle,
	Toc,
	ToastProvider,
}

interface Props {
	source: string
}

export async function MDX({ source }: Props) {
	return (
		<MDXRemote
			source={source}
			components={components}
			options={{
				mdxOptions: {
					remarkPlugins: [remarkGfm, remarkAlerts],
					rehypePlugins: [
						rehypeAnchors,
						[
							rehypeShiki,
							{
								themes: {
									light: "github-light",
									dark: "github-dark-default",
								},
								defaultColor: false,
								transformers: [
									transformerMetaHighlight(),
									transformerNotationHighlight(),
									transformerNotationDiff(),
									transformerNotationFocus(),
									transformerNotationWordHighlight(),
									transformerCollapse(),
									{
										pre(
											this: ShikiTransformerContext,
											node: { properties: Record<string, string> },
										) {
											const lang = this.options.lang || ""
											if (lang) {
												node.properties["data-language"] = lang
											}
											const meta = this.options.meta?.__raw || ""
											const match = meta.match(/title="([^"]*)"/)
											if (match) {
												node.properties["data-title"] = match[1]!
											}
										},
									},
								],
							},
						],
					],
				},
			}}
		/>
	)
}
